# -*- coding: utf-8 -*-
"""struct-to-dict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183kSGAcQbtujITNQHnVKfmiJ9GD6GdQ1

struct to dictionary
"""

name="Rahul"
roll=101
marks=87.5

print("Name:",name)
print("Roll:",roll)
print("Marks:",format(marks,".1f"))